preload = /home/sachin/.config/hypr/assets/Wallpaper Alchemy - Arch Linux Sweet KDE 4K Wallpaper.jpeg

wallpaper {
    monitor = 
    path = /home/sachin/.config/hypr/assets/Wallpaper Alchemy - Arch Linux Sweet KDE 4K Wallpaper.jpeg
    fit_mode = cover
}

